from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from datetime import datetime
import os

class MedicalReportGenerator:
    def __init__(self, output_path):
        self.output_path = output_path
        self.styles = getSampleStyleSheet()
        self.custom_style = ParagraphStyle(
            'CustomStyle',
            parent=self.styles['Normal'],
            fontSize=12,
            leading=14,
            spaceAfter=10
        )

    def generate(self, data):
        """
        data: dictionary containing report details:
        {
            'patient_name': '...',
            'analysis_type': '...',
            'prediction': '...',
            'confidence': '...',
            'severity': '...',
            'notes': '...',
            'image_path': '...',
            'heatmap_path': '...'
        }
        """
        doc = SimpleDocTemplate(self.output_path, pagesize=letter)
        elements = []

        # Header
        elements.append(Paragraph("AI Diagnostic Report", self.styles['Title']))
        elements.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", self.styles['Normal']))
        elements.append(Spacer(1, 12))

        # Patient Info
        elements.append(Paragraph("<b>Analysis Details</b>", self.styles['Heading2']))
        patient_data = [
            ["Analysis Type", data.get('analysis_type', 'N/A')],
            ["Diagnosis", data.get('prediction', 'N/A')],
            ["Confidence", f"{data.get('confidence', 0)*100:.2f}%"],
            ["Severity", data.get('severity', 'N/A')]
        ]
        t = Table(patient_data, colWidths=[150, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 12))

        # Images
        if data.get('image_path') and os.path.exists(data['image_path']):
            elements.append(Paragraph("<b>Input Image & Heatmap</b>", self.styles['Heading2']))
            # Add images side-by-side if possible, or one after another
            img = Image(data['image_path'], width=200, height=200)
            elements.append(img)
            elements.append(Spacer(1, 12))
            
            if data.get('heatmap_path') and os.path.exists(data['heatmap_path']):
                heat_img = Image(data['heatmap_path'], width=200, height=200)
                elements.append(heat_img)
                elements.append(Paragraph("<i>Heatmap showing areas of clinical interest.</i>", self.styles['Italic']))

        elements.append(Spacer(1, 12))

        # Clinical Notes
        elements.append(Paragraph("<b>Clinical Notes & Recommendations</b>", self.styles['Heading2']))
        elements.append(Paragraph(data.get('notes', 'No additional notes provided.'), self.custom_style))

        # Footer
        elements.append(Spacer(1, 24))
        elements.append(Paragraph("Disclaimer: This report is generated by an AI system for clinical support. Final diagnosis must be confirmed by a certified medical professional.", self.styles['Italic']))

        doc.build(elements)
        return self.output_path
